# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b8048bb536efc349a25243fec1c254d7ea291bf3533e9a627eaabd00b0b39b2c536bb73a540428cb69abab2d709c27371c3d5ea270e774f65b8d0ba8a30ff79

test:
  secret_key_base: 0c4e52cb33159f381fe82dc98863caece4798dcf6e97e2807d76c0d629bc498483e945f61ddea33870316af936d9a8d686ab547efc6286eadd812940d251ecde

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
